site_name: CrewPackXP
site_url: https://github.com/N1K340/CrewPackXP
nav:
  - Home: index.md
  - Flight Factor 757 / 767:
    - About: about.md
    - Changelog: changelog.md
    - License: license.md
theme: readthedocs

